# Workflow name
name: Deploy to GitHub Pages

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  # The 'build' job is responsible for building the project and creating an artifact
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify a Node.js version

      - name: Install dependencies
        # Caches dependencies to speed up future builds
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          # The path should match your build output directory (e.g., dist, build)
          path: ./dist

  # The 'deploy' job is responsible for deploying the artifact to GitHub Pages
  deploy:
    name: Deploy
    # This job depends on the 'build' job completing successfully
    needs: build
    runs-on: ubuntu-latest

    # ❗ CRITICAL: Grant 'write' permissions to this job so it can push to the gh-pages branch
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          # No path needed, it will download to the current directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The directory to publish is the root, as the artifact was downloaded here
          publish_dir: .
